// web-service/components/DayBox.tsx
import { Fragment, useEffect, useState } from "react";
import { toLocaleDateString } from "../utils/common";
import { DayMenu, Weekday } from "../utils/getWeekMenu";
import styles from "./css/DayBox.module.scss";

interface IProps {
  dayName: string;
  menu?: DayMenu;
  date?: Date;
  isToday?: boolean;
}

export default function DayBox(props: IProps) {
  const [date, setDate] = useState("...");

  useEffect(() => {
    if (props.date) {
      setDate(toLocaleDateString(props.date))
    } else if (props.menu?.date) {
      setDate(toLocaleDateString(new Date(props.menu.date)))
    }
  }, [props.menu?.date, props.date])

  return (
    <div className={styles.container + " " + (props.isToday ? styles.today : "")}>
      <h2 className={styles["day-name"]}>{props.dayName}</h2>
      <div className={styles.break}></div>
      <div className={styles.box}>
        <p className={styles.date}>{date}</p>
        <ul className={styles["menu-list"]}>
          {
            props.menu?.menu.map((meal, index) => {
              return (
                <Fragment key={index}>
                  <li key={index} className={styles.menuListItem}>
                    {
                      meal.names.map((name, index) => {
                        const diets = meal.diets[index];
      
                        return (
                          <>
                            <span style={{marginRight: ".5em"}}>{name}</span>
                            <div className={styles["food-diets"]}>
                              {diets.isLactoseFree ? <Diet longName="Laktoositon">L</Diet> : <></>}
                              {diets.isDairyFree ? <Diet longName="Maidoton">M</Diet> : <></>}
                              {diets.isGlutenFree ? <Diet longName="Gluteeniton">G</Diet> : <></>}
                            </div>
                          </>
                        );
                      })
                    }
                  </li>
                </Fragment>
              );
            })
          }
        </ul>
        {
          props.menu ? <></> : <p style={{ textAlign: "center" }}>Ei saatavilla</p>
        }
      </div>
    </div>
  )
}

export function Diet(props: { children: string, longName?: string }) {
  return (
    <span className={styles.diet} style={{cursor: props.longName ? "pointer" : "default"}}>
      {props.children}
      {props.longName ? <div className={styles["diet-tooltip"]}>{props.longName}</div> : <></>}
    </span>
  )
}

// safka/src/routes/DayBox.svelte
<script lang="ts">
	import type { ISODateString, Meal } from "../types";
    import { format, parseISO } from "date-fns";
	import DietChip from "./DietChip.svelte";
	import { formatDate } from "$lib/utils";

    export let date: ISODateString;
    export let menu: Meal[];
    export let dayName: string;
    export let isToday: boolean;

    const formattedDate = formatDate(parseISO(date));
</script>

<div class="container" data-is-today={isToday}>
    <h1 class="day-name">{dayName}</h1>
    <div class="divider"></div>
    <div class="box">
        <p class="date">{formattedDate}</p>
        <ul>
            {#each menu as meal}
                <li>
                    {#each meal.names as name, index}
                        <span>{name}</span>
                        {#if meal.diets[index].isLactoseFree}
                            <DietChip name="Laktoositon" letter="L" />
                        {:else if meal.diets[index].isDairyFree}
                            <DietChip name="Maidoton" letter="M" />
                        {:else if meal.diets[index].isGlutenFree}
                            <DietChip name="Gluteeniton" letter="G" />
                        {/if}
                    {/each}
                </li>
            {/each}
    </div>
</div>


<style lang="scss">
    .container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 16px;

        width: 300px;
        height: 450px;

        &[data-is-today=true] {
            .box {
                border-color: var(--primary);
            }
        } 
    }

    .day-name {
        color: var(--on-background-header);
    }

    .divider {
        width: calc(100% - 16px * 2);
        height: 1px;

        background-color: var(--surface-variant);
    }

    .box {
        width: 100%;
        flex: 1;
        padding: 8px;
        border-radius: 24px;
        border: 12px solid transparent;
        box-sizing: border-box;
        box-shadow: 17px 17px 32px rgba(0, 0, 0, .145), -17px -17px 32px rgba(0, 0, 0, .035);

        background-color: var(--background);
        color: var(--on-surface);
    }
</style>
